resources:
- name: flight-school
  type: git
  source:
    branch: master
    uri: https://github.com/srinikan/flight-school.git
- name: staging-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    organization: CCSDemo-org
    username: sprabhukrishna@gmail.com
    password: Cl0ud@123
    skip_cert_check: true
    space: pcfcogspace 

jobs:
- name: test-app
  serial: true
  public: true
  plan:
  - get: flight-school
    trigger: true 
  - task: tests
    file: https://github.com/srinikan/flight-school/build.yml
  - put: staging-app
    params:
      manifest: https://github.com/srinikan/flight-school/manifest.yml
