resources:
- name: flight-school
  type: git
  source:
    branch: master
    uri: https://github.com/srinikan/flight-school

- name: stagingsrk-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    organization: CCSDemo-org
    username: sprabhukrishna@gmail.com
    password: Cl0ud@123
    skip_cert_check: true
    space: pcfcogspace 

jobs:
- name: stagingsrk-app
  plan:
  - get: flight-school
    trigger: true 
  - task: tests
    file: flight-school/build.yml
  - put: stagingsrk-app
    params:
      manifest: flight-school/manifest.yml
